#!/usr/bin/env python3
"""
Insert sample storage locations from results/sample-storage.csv into research.db.

The CSV is generated by generate_experiment.py for procedures that produce new
samples. Fill in freezer, drawer, box, and position after storing the samples,
then run this script.

Usage:
    python3 scripts/insert_sample_storage.py <project_id> <date> <experiment_name>

Arguments:
    project_id       : 1=MATRX, 2=small-genes, 3=diabetic-small-genes,
                       4=MitoPilot, 5=COMIT, 6=SPRAT
    date             : YYYY-MM-DD (must match the experiment directory date)
    experiment_name  : kebab-case name used when generating the experiment
                       (e.g. 'mito-rna-extractions')

Example:
    python3 scripts/insert_sample_storage.py 2 2026-04-17 mito-rna-extractions
"""

import csv
import sqlite3
import sys
from pathlib import Path

PROJECT_DIRS = {
    1: "MATRX-study",
    2: "small-genes-with-big-potential",
    3: "diabetic-small-genes",
    4: "MitoPilot",
    5: "COMIT",
    6: "SPRAT",
}


def nullable_str(val):
    return val.strip() or None


if len(sys.argv) != 4:
    sys.exit(__doc__)

project_id    = int(sys.argv[1])
date          = sys.argv[2]
exp_name      = sys.argv[3]

project_dir = PROJECT_DIRS.get(project_id)
if not project_dir:
    sys.exit(f"ERROR: unknown project_id {project_id}. Valid: {list(PROJECT_DIRS)}")

csv_path = (
    Path("projects") / project_dir / "lab-notebook" / "experiments"
    / f"{date}_{exp_name}" / "results" / "sample-storage.csv"
)

if not csv_path.exists():
    sys.exit(f"ERROR: CSV not found: {csv_path}")

db = sqlite3.connect("research.db")
db.execute("PRAGMA foreign_keys = ON")

inserted = 0
skipped  = 0

with open(csv_path, newline="") as f:
    reader = csv.DictReader(f)
    for row in reader:
        sample_id = row["sample_id"].strip()
        if not sample_id:
            continue

        # Verify sample exists in DB
        exists = db.execute(
            "SELECT 1 FROM samples WHERE sample_id = ?", (sample_id,)
        ).fetchone()
        if not exists:
            print(f"WARNING: sample_id not in DB, skipping: {sample_id}")
            skipped += 1
            continue

        # Guard against re-running the script on the same experiment
        duplicate = db.execute(
            "SELECT 1 FROM sample_storage WHERE sample_id = ? AND date = ?",
            (sample_id, row.get("date", "").strip())
        ).fetchone()
        if duplicate:
            print(f"Skipping duplicate: {sample_id} already stored on {row.get('date', '').strip()}")
            skipped += 1
            continue

        db.execute(
            """
            INSERT INTO sample_storage (sample_id, freezer, drawer, box, position, date, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                sample_id,
                nullable_str(row.get("freezer", "")),
                nullable_str(row.get("drawer", "")),
                nullable_str(row.get("box", "")),
                nullable_str(row.get("position", "")),
                nullable_str(row.get("date", "")),
                nullable_str(row.get("notes", "")),
            ),
        )
        inserted += 1

db.commit()
db.close()

print(f"Inserted {inserted} storage record(s) into sample_storage.")
if skipped:
    print(f"Skipped {skipped} row(s) — sample_id not found in DB.")
